#!/usr/local/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from pip._internal.cli.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    if len(sys.argv) > 1 and sys.argv[1] == 'install':
        sys.argv.insert(2, '--user')
    sys.exit(main())
